In [2]:
import numpy as np

In [3]:
myList = [1,2,3]
x = np.array(myList)
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [5]:
m = np.array([x,y])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.shape(m)

(2, 3)

In [7]:
xx = np.arange(0,100,2)
xx

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
xx = xx.reshape(10,5)
xx.reshape(1,50)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
        64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94,
        96, 98]])

In [9]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [13]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [24]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [31]:
p = np.ones([4,5], int)
p

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.vstack([p,p*5])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [34]:
np.hstack([p,p*2,p*3])

array([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]])

In [38]:
x = np.arange(1,4)
y = np.arange(4,7)

In [39]:
x+y

array([5, 7, 9])

In [40]:
x-y

array([-3, -3, -3])

In [41]:
x*y

array([ 4, 10, 18])

In [42]:
x/y

array([0.25, 0.4 , 0.5 ])

In [43]:
x**y

array([  1,  32, 729], dtype=int32)

In [44]:
x.dot(y)

32

In [52]:
xy = np.array([y,y*10])
xy

array([[ 4,  5,  6],
       [40, 50, 60]])

In [57]:
xy = xy.T
xy

array([[ 4, 40],
       [ 5, 50],
       [ 6, 60]])

In [58]:
xy.dtype

dtype('int32')

In [62]:
xy.astype('f')

array([[ 4., 40.],
       [ 5., 50.],
       [ 6., 60.]], dtype=float32)

In [118]:
urutan = np.random.rand(1,100)*100
urutan = urutan.astype('int')

In [119]:
urutan.sum() == np.sum(urutan)

True

In [120]:
urutan.min()

0

In [113]:
urutan.max()

99

In [114]:
urutan.mean()

51.51

In [115]:
urutan.std() # standard deviation

30.379432186925417

In [116]:
urutan.argmax() # index lokasi nilai maks

22

In [121]:
urutan.argmin() # index lokasi nilai min

7

In [134]:
r = np.arange(20)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [135]:
r[-4:-2]

array([16, 17])

In [136]:
r[-5::2]

array([15, 17, 19])

In [138]:
r.resize(4,5)
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [140]:
r[1,2] == 7

True

In [143]:
r[3,2:4]

array([17, 18])

In [150]:
r[2:,::2]

array([[10, 12, 14],
       [15, 17, 19]])

In [152]:
r[r>15]

array([16, 17, 18, 19])

In [163]:
array1 = np.arange(20)
array1 = array1.reshape(5,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [162]:
array2 = array1 # array2 dirubah, array1 ikut berubah

array2[0,1] = 0
array1

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [166]:
array2 = array1.copy()
array2[0,1] = 0
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [179]:
random_array = np.random.randint(0,30,[5,6])
random_array

array([[ 5, 24, 18, 23, 18,  1],
       [ 5, 14,  6,  8, 16, 27],
       [25,  0, 12, 22, 12,  9],
       [20, 17, 13, 10, 24, 18],
       [ 7, 15,  8, 29, 20,  0]])

In [180]:
for data in random_array:
    print(data)

[ 5 24 18 23 18  1]
[ 5 14  6  8 16 27]
[25  0 12 22 12  9]
[20 17 13 10 24 18]
[ 7 15  8 29 20  0]


In [181]:
for i in range(len(random_array)):
    print(random_array[i])

[ 5 24 18 23 18  1]
[ 5 14  6  8 16 27]
[25  0 12 22 12  9]
[20 17 13 10 24 18]
[ 7 15  8 29 20  0]


In [182]:
for i, data in enumerate(random_array):
    print('baris',i,'datanya',data)

baris 0 datanya [ 5 24 18 23 18  1]
baris 1 datanya [ 5 14  6  8 16 27]
baris 2 datanya [25  0 12 22 12  9]
baris 3 datanya [20 17 13 10 24 18]
baris 4 datanya [ 7 15  8 29 20  0]


In [183]:
random_array2 = random_array**2
random_array2

array([[ 25, 576, 324, 529, 324,   1],
       [ 25, 196,  36,  64, 256, 729],
       [625,   0, 144, 484, 144,  81],
       [400, 289, 169, 100, 576, 324],
       [ 49, 225,  64, 841, 400,   0]], dtype=int32)

In [184]:
for i, j in zip(random_array,random_array2):
    print(i,'+',j,'=',i+j)

[ 5 24 18 23 18  1] + [ 25 576 324 529 324   1] = [ 30 600 342 552 342   2]
[ 5 14  6  8 16 27] + [ 25 196  36  64 256 729] = [ 30 210  42  72 272 756]
[25  0 12 22 12  9] + [625   0 144 484 144  81] = [650   0 156 506 156  90]
[20 17 13 10 24 18] + [400 289 169 100 576 324] = [420 306 182 110 600 342]
[ 7 15  8 29 20  0] + [ 49 225  64 841 400   0] = [ 56 240  72 870 420   0]


In [186]:
[1,2,3]+[1,2,3]

[1, 2, 3, 1, 2, 3]

In [189]:
lambdda = lambda x: x+x
type(lambdda)

function

In [190]:
[a for a in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [196]:
r = np.arange(0,36)
r = r.reshape(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [198]:
np.arange(0,36)[::7]


array([ 0,  7, 14, 21, 28, 35])

In [199]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])